version: '3.9'

services:
  app:
    build: .
    container_name: resllerscript-app
    volumes:
      - .:/var/www/html
      - logs:/var/www/html/storage/logs
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: resellerscript
      DB_USER: reseller
      DB_PASS: secret
      LOG_DIR: /var/www/html/storage/logs
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: resllerscript-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: resellerscript
      MYSQL_USER: reseller
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  logs:
  db_data:
